/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.1.0.4875
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddAlbumOptions {
    #[serde(rename = "addType", skip_serializing_if = "Option::is_none")]
    pub add_type: Option<models::AlbumAddType>,
    #[serde(rename = "searchForNewAlbum", skip_serializing_if = "Option::is_none")]
    pub search_for_new_album: Option<bool>,
}

impl AddAlbumOptions {
    pub fn new() -> AddAlbumOptions {
        AddAlbumOptions {
            add_type: None,
            search_for_new_album: None,
        }
    }
}

