/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v2.9.6.4552
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumStudioArtistResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "monitored", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monitored: Option<Option<bool>>,
    #[serde(rename = "albums", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub albums: Option<Option<Vec<models::AlbumResource>>>,
}

impl AlbumStudioArtistResource {
    pub fn new() -> AlbumStudioArtistResource {
        AlbumStudioArtistResource {
            id: None,
            monitored: None,
            albums: None,
        }
    }
}

