/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v2.9.6.4552
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ArtistStatusType>,
    #[serde(rename = "ended", skip_serializing_if = "Option::is_none")]
    pub ended: Option<bool>,
    #[serde(rename = "artistName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub artist_name: Option<Option<String>>,
    #[serde(rename = "foreignArtistId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub foreign_artist_id: Option<Option<String>>,
    #[serde(rename = "mbId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mb_id: Option<Option<String>>,
    #[serde(rename = "tadbId", skip_serializing_if = "Option::is_none")]
    pub tadb_id: Option<i32>,
    #[serde(rename = "discogsId", skip_serializing_if = "Option::is_none")]
    pub discogs_id: Option<i32>,
    #[serde(rename = "allMusicId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub all_music_id: Option<Option<String>>,
    #[serde(rename = "overview", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub overview: Option<Option<String>>,
    #[serde(rename = "artistType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub artist_type: Option<Option<String>>,
    #[serde(rename = "disambiguation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub disambiguation: Option<Option<String>>,
    #[serde(rename = "links", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub links: Option<Option<Vec<models::Links>>>,
    #[serde(rename = "nextAlbum", skip_serializing_if = "Option::is_none")]
    pub next_album: Option<Box<models::AlbumResource>>,
    #[serde(rename = "lastAlbum", skip_serializing_if = "Option::is_none")]
    pub last_album: Option<Box<models::AlbumResource>>,
    #[serde(rename = "images", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub images: Option<Option<Vec<models::MediaCover>>>,
    #[serde(rename = "members", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub members: Option<Option<Vec<models::Member>>>,
    #[serde(rename = "remotePoster", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remote_poster: Option<Option<String>>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "qualityProfileId", skip_serializing_if = "Option::is_none")]
    pub quality_profile_id: Option<i32>,
    #[serde(rename = "metadataProfileId", skip_serializing_if = "Option::is_none")]
    pub metadata_profile_id: Option<i32>,
    #[serde(rename = "monitored", skip_serializing_if = "Option::is_none")]
    pub monitored: Option<bool>,
    #[serde(rename = "monitorNewItems", skip_serializing_if = "Option::is_none")]
    pub monitor_new_items: Option<models::NewItemMonitorTypes>,
    #[serde(rename = "rootFolderPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub root_folder_path: Option<Option<String>>,
    #[serde(rename = "folder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub folder: Option<Option<String>>,
    #[serde(rename = "genres", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Option<Vec<String>>>,
    #[serde(rename = "cleanName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub clean_name: Option<Option<String>>,
    #[serde(rename = "sortName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sort_name: Option<Option<String>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<i32>>>,
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<String>,
    #[serde(rename = "addOptions", skip_serializing_if = "Option::is_none")]
    pub add_options: Option<Box<models::AddArtistOptions>>,
    #[serde(rename = "ratings", skip_serializing_if = "Option::is_none")]
    pub ratings: Option<Box<models::Ratings>>,
    #[serde(rename = "statistics", skip_serializing_if = "Option::is_none")]
    pub statistics: Option<Box<models::ArtistStatisticsResource>>,
}

impl ArtistResource {
    pub fn new() -> ArtistResource {
        ArtistResource {
            id: None,
            status: None,
            ended: None,
            artist_name: None,
            foreign_artist_id: None,
            mb_id: None,
            tadb_id: None,
            discogs_id: None,
            all_music_id: None,
            overview: None,
            artist_type: None,
            disambiguation: None,
            links: None,
            next_album: None,
            last_album: None,
            images: None,
            members: None,
            remote_poster: None,
            path: None,
            quality_profile_id: None,
            metadata_profile_id: None,
            monitored: None,
            monitor_new_items: None,
            root_folder_path: None,
            folder: None,
            genres: None,
            clean_name: None,
            sort_name: None,
            tags: None,
            added: None,
            add_options: None,
            ratings: None,
            statistics: None,
        }
    }
}

