/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.0.1.4866
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArtistStatusType {
    #[serde(rename = "continuing")]
    Continuing,
    #[serde(rename = "ended")]
    Ended,
    #[serde(rename = "deleted")]
    Deleted,

}

impl std::fmt::Display for ArtistStatusType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Continuing => write!(f, "continuing"),
            Self::Ended => write!(f, "ended"),
            Self::Deleted => write!(f, "deleted"),
        }
    }
}

impl Default for ArtistStatusType {
    fn default() -> ArtistStatusType {
        Self::Continuing
    }
}

