/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.0.1.4866
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileDateType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "albumReleaseDate")]
    AlbumReleaseDate,

}

impl std::fmt::Display for FileDateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::AlbumReleaseDate => write!(f, "albumReleaseDate"),
        }
    }
}

impl Default for FileDateType {
    fn default() -> FileDateType {
        Self::None
    }
}

