/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.0.1.4866
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportListExclusionResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "foreignId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub foreign_id: Option<Option<String>>,
    #[serde(rename = "artistName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub artist_name: Option<Option<String>>,
}

impl ImportListExclusionResource {
    pub fn new() -> ImportListExclusionResource {
        ImportListExclusionResource {
            id: None,
            foreign_id: None,
            artist_name: None,
        }
    }
}

