/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v2.9.6.4552
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImportListMonitorType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "specificAlbum")]
    SpecificAlbum,
    #[serde(rename = "entireArtist")]
    EntireArtist,

}

impl std::fmt::Display for ImportListMonitorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::SpecificAlbum => write!(f, "specificAlbum"),
            Self::EntireArtist => write!(f, "entireArtist"),
        }
    }
}

impl Default for ImportListMonitorType {
    fn default() -> ImportListMonitorType {
        Self::None
    }
}

