/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.0.1.4866
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImportListType {
    #[serde(rename = "program")]
    Program,
    #[serde(rename = "spotify")]
    Spotify,
    #[serde(rename = "lastFm")]
    LastFm,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "advanced")]
    Advanced,

}

impl std::fmt::Display for ImportListType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Program => write!(f, "program"),
            Self::Spotify => write!(f, "spotify"),
            Self::LastFm => write!(f, "lastFm"),
            Self::Other => write!(f, "other"),
            Self::Advanced => write!(f, "advanced"),
        }
    }
}

impl Default for ImportListType {
    fn default() -> ImportListType {
        Self::Program
    }
}

