/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.0.1.4866
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualImportUpdateResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "artistId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub artist_id: Option<Option<i32>>,
    #[serde(rename = "albumId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub album_id: Option<Option<i32>>,
    #[serde(rename = "albumReleaseId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub album_release_id: Option<Option<i32>>,
    #[serde(rename = "tracks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Option<Vec<models::TrackResource>>>,
    #[serde(rename = "trackIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub track_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<Box<models::QualityModel>>,
    #[serde(rename = "releaseGroup", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_group: Option<Option<String>>,
    #[serde(rename = "indexerFlags", skip_serializing_if = "Option::is_none")]
    pub indexer_flags: Option<i32>,
    #[serde(rename = "downloadId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub download_id: Option<Option<String>>,
    #[serde(rename = "additionalFile", skip_serializing_if = "Option::is_none")]
    pub additional_file: Option<bool>,
    #[serde(rename = "replaceExistingFiles", skip_serializing_if = "Option::is_none")]
    pub replace_existing_files: Option<bool>,
    #[serde(rename = "disableReleaseSwitching", skip_serializing_if = "Option::is_none")]
    pub disable_release_switching: Option<bool>,
    #[serde(rename = "rejections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejections: Option<Option<Vec<models::Rejection>>>,
}

impl ManualImportUpdateResource {
    pub fn new() -> ManualImportUpdateResource {
        ManualImportUpdateResource {
            id: None,
            path: None,
            name: None,
            artist_id: None,
            album_id: None,
            album_release_id: None,
            tracks: None,
            track_ids: None,
            quality: None,
            release_group: None,
            indexer_flags: None,
            download_id: None,
            additional_file: None,
            replace_existing_files: None,
            disable_release_switching: None,
            rejections: None,
        }
    }
}

