/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v2.9.6.4552
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamingConfigResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "renameTracks", skip_serializing_if = "Option::is_none")]
    pub rename_tracks: Option<bool>,
    #[serde(rename = "replaceIllegalCharacters", skip_serializing_if = "Option::is_none")]
    pub replace_illegal_characters: Option<bool>,
    #[serde(rename = "colonReplacementFormat", skip_serializing_if = "Option::is_none")]
    pub colon_replacement_format: Option<i32>,
    #[serde(rename = "standardTrackFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_track_format: Option<Option<String>>,
    #[serde(rename = "multiDiscTrackFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub multi_disc_track_format: Option<Option<String>>,
    #[serde(rename = "artistFolderFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub artist_folder_format: Option<Option<String>>,
    #[serde(rename = "includeArtistName", skip_serializing_if = "Option::is_none")]
    pub include_artist_name: Option<bool>,
    #[serde(rename = "includeAlbumTitle", skip_serializing_if = "Option::is_none")]
    pub include_album_title: Option<bool>,
    #[serde(rename = "includeQuality", skip_serializing_if = "Option::is_none")]
    pub include_quality: Option<bool>,
    #[serde(rename = "replaceSpaces", skip_serializing_if = "Option::is_none")]
    pub replace_spaces: Option<bool>,
    #[serde(rename = "separator", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub separator: Option<Option<String>>,
    #[serde(rename = "numberStyle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub number_style: Option<Option<String>>,
}

impl NamingConfigResource {
    pub fn new() -> NamingConfigResource {
        NamingConfigResource {
            id: None,
            rename_tracks: None,
            replace_illegal_characters: None,
            colon_replacement_format: None,
            standard_track_format: None,
            multi_disc_track_format: None,
            artist_folder_format: None,
            include_artist_name: None,
            include_album_title: None,
            include_quality: None,
            replace_spaces: None,
            separator: None,
            number_style: None,
        }
    }
}

