/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.1.0.4875
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParseResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "parsedAlbumInfo", skip_serializing_if = "Option::is_none")]
    pub parsed_album_info: Option<Box<models::ParsedAlbumInfo>>,
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<Box<models::ArtistResource>>,
    #[serde(rename = "albums", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub albums: Option<Option<Vec<models::AlbumResource>>>,
    #[serde(rename = "customFormats", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_formats: Option<Option<Vec<models::CustomFormatResource>>>,
    #[serde(rename = "customFormatScore", skip_serializing_if = "Option::is_none")]
    pub custom_format_score: Option<i32>,
}

impl ParseResource {
    pub fn new() -> ParseResource {
        ParseResource {
            id: None,
            title: None,
            parsed_album_info: None,
            artist: None,
            albums: None,
            custom_formats: None,
            custom_format_score: None,
        }
    }
}

