/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.1.0.4875
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileSecondaryAlbumTypeItemResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "albumType", skip_serializing_if = "Option::is_none")]
    pub album_type: Option<Box<models::SecondaryAlbumType>>,
    #[serde(rename = "allowed", skip_serializing_if = "Option::is_none")]
    pub allowed: Option<bool>,
}

impl ProfileSecondaryAlbumTypeItemResource {
    pub fn new() -> ProfileSecondaryAlbumTypeItemResource {
        ProfileSecondaryAlbumTypeItemResource {
            id: None,
            album_type: None,
            allowed: None,
        }
    }
}

