/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.1.0.4875
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ratings {
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<i32>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
}

impl Ratings {
    pub fn new() -> Ratings {
        Ratings {
            votes: None,
            value: None,
        }
    }
}

