/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: v3.1.0.4875
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReleaseStatus {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl ReleaseStatus {
    pub fn new() -> ReleaseStatus {
        ReleaseStatus {
            id: None,
            name: None,
        }
    }
}

